### ISSUE TITLE
[Feature] Please expose a function equivalent of the "..._lower_rest()" functions without the title casing

### ISSUE THREAD

**Issue by alerque** [Teh-Bobo/unicode-title-case#11]
The function `to_titlecase_tr_or_az_lower_rest()` is great, but I'm trying to use this library to make something that actually handles title phrases rather than just single word strings. That means handling things word by word and checking for words such as conjunctions or the question suffix (which appears as a separate word) and excluding them from title casing. In the event of an all caps string, this means *lower casing* those words.

It would be helpful if this library exposed something like a `to_lowercase_tr_or_az()` that would use the same logic for lowercasing without also title casing the first letter.

**Comment by Teh-Bobo** [comment]
@alerque I've got a draft going in the feature branch that I think meets what you're looking for if you want to take a look. I still need to add comments and tests.

**Comment by alerque** [comment]
Wow, that looks great. Nice to see the matching uppercase function too. I haven't given it a test drive yet but from reviewing [the branch](https://github.com/Teh-Bobo/unicode-title-case/compare/11-feature-please-expose-an) I'd say it looks like it will suit me fine.

I was curious my you used `#[must_use]` for the lower case function but not the upper, but that might be a case of my Rust foo being weak.

If you haven't seen it, I'm using these character level tools to build a tool for title casing whole strings using grammatical rules. You can check it out in the [decasify](https://github.com/alerque/decasify/) repo. The English grammar rules for titles are complicated so an implementation may never be fully robust, but Turkish is a lot easier am I'm hopeful for a 99% or so reliable way to normalize titles. Right now it handles most of the grammatical rules, but I haven't setup punctuation handling yet.

The TR title casing for full title strings was an urgent need for production work so that is wired up first, but I'd like to improve the ergonomics a bit and make other cases work too. Input on the Rust interfaces is welcome if you have any interest.

**Comment by Teh-Bobo** [comment]
Good to hear. The missing `#[must_use]` was a mistake, I've corrected it in the next commit. I'll make sure to give yours a look and leave any thoughts over there.
