### ISSUE TITLE
Turkish title case function produces incorrect output

### ISSUE THREAD

**Issue by alerque** [Teh-Bobo/unicode-title-case#9]
The function that lower cases text beyond the first letter doesn't handle Turkish undotted-I's correctly. The example in the readme even shows the issue:

```rust
assert_eq!("iIi".to_titlecase_tr_or_az_lower_rest(), "İii");
```

The output needs to have two different lower case letters like this:

```rust
assert_eq!("iIi".to_titlecase_tr_or_az_lower_rest(), "İıi");
```

**Comment by Teh-Bobo** [comment]
Thank you for catching this! I believe this patch should fix it, but if it doesn't then feel free to re-open it.
